### ISSUE TITLE
problems with Tibbles

### ISSUE THREAD

**Issue by parguel** [FRBCesab/popbayes#30] opened 2023-06-14 13:33 UTC
in format_data, if argument data is a tibble, it will pass the test "data must be a data.frame", but will fail the test 
"The column date must be numeric" (subsetting rules are different and yield a tibble instead of a vector).

Suggested solution: after the initial test  "data must be a data.frame", add the line
data <- as.data.frame(data)

**Comment by ahasverus** [comment] 2023-06-15 06:36
Duplicate of #29

**Closed as completed by ahasverus** 2023-06-15 06:36 UTC
